// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TagemEgitim.Models;

namespace TagemEgitim.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200821090529_mig02")]
    partial class mig02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TagemEgitim.Models.Kişi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cinsiyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("doğumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("görev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ülkeID")
                        .HasColumnType("int");

                    b.Property<int?>("ünvanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ülkeID");

                    b.HasIndex("ünvanID");

                    b.ToTable("Kişiler");
                });

            modelBuilder.Entity("TagemEgitim.Models.KişiKurs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diğerKatılım")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("katılımŞekli")
                        .HasColumnType("int");

                    b.Property<int>("kişiID")
                        .HasColumnType("int");

                    b.Property<int>("kursID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("kişiID");

                    b.HasIndex("kursID");

                    b.ToTable("kişikurs");
                });

            modelBuilder.Entity("TagemEgitim.Models.Kullar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("admin")
                        .HasColumnType("bit");

                    b.Property<string>("adminCode")
                        .HasColumnType("nvarchar(600)")
                        .HasMaxLength(600);

                    b.Property<string>("cerez")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("cerezEnc")
                        .HasColumnType("nvarchar(600)")
                        .HasMaxLength(600);

                    b.Property<int>("hatali")
                        .HasColumnType("int");

                    b.Property<bool>("hatirla")
                        .HasColumnType("bit");

                    b.Property<DateTime>("kilitliTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("kulname")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("kulpass")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("kulpassEnc")
                        .HasColumnType("nvarchar(600)")
                        .HasMaxLength(600);

                    b.HasKey("ID");

                    b.ToTable("Kullar");
                });

            modelBuilder.Entity("TagemEgitim.Models.Kurs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("basvuruBaslama")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("basvuruBitis")
                        .HasColumnType("datetime2");

                    b.Property<bool>("basvuruDuraklat")
                        .HasColumnType("bit");

                    b.Property<int>("basvuruSuresi")
                        .HasColumnType("int");

                    b.Property<int>("evtürü")
                        .HasColumnType("int");

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isimEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kursSuresi")
                        .HasColumnType("int");

                    b.Property<string>("notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tarihBasla")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tarihBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("toplantıtürü")
                        .HasColumnType("int");

                    b.Property<int>("ulustürü")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("TagemEgitim.Models.Obscure", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KursID")
                        .HasColumnType("int");

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sayı")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KursID");

                    b.ToTable("Obscures");
                });

            modelBuilder.Entity("TagemEgitim.Models.Ülke", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ülkeler");
                });

            modelBuilder.Entity("TagemEgitim.Models.Ünvan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ünvanlar");
                });

            modelBuilder.Entity("TagemEgitim.Models.Kişi", b =>
                {
                    b.HasOne("TagemEgitim.Models.Ülke", "ülke")
                        .WithMany()
                        .HasForeignKey("ülkeID");

                    b.HasOne("TagemEgitim.Models.Ünvan", "ünvan")
                        .WithMany()
                        .HasForeignKey("ünvanID");
                });

            modelBuilder.Entity("TagemEgitim.Models.KişiKurs", b =>
                {
                    b.HasOne("TagemEgitim.Models.Kişi", "kişi")
                        .WithMany("kişikurs")
                        .HasForeignKey("kişiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TagemEgitim.Models.Kurs", "kurs")
                        .WithMany("kişikurs")
                        .HasForeignKey("kursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagemEgitim.Models.Obscure", b =>
                {
                    b.HasOne("TagemEgitim.Models.Kurs", null)
                        .WithMany("obscures")
                        .HasForeignKey("KursID");
                });
#pragma warning restore 612, 618
        }
    }
}
